version: '3'
services:
    laravel.test:
        build:
            context: ./infra/docker
            dockerfile: ./ubuntu/Dockerfile
            args:
                WWWGROUP: 1000
        image: ubuntu:latest
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
            - '5173:5173'
        environment:
            WWWUSER: 'sail'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '-off'
            XDEBUG_CONFIG: '-client_host=host.docker.internal'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
networks:
    sail:
        driver: bridge