version: "3.9"
services:
    nginx:
        build:
            context: ./docker/nginx/
            dockerfile: ./Dockerfile
        ports:
            - 80:8080
        depends_on:
            - php
        volumes:
            - ./contents:/usr/share/nginx/html
    php:
        image: php:8-fpm
        build:
            context: ./docker/php/
            dockerfile: ./Dockerfile
        volumes:
            - ./    :/usr/share/nginx/html