version: "3"
services:
    nginx:
        build: .
        ports:
            - 8080:8080
        volumes:
            - ./contents:/usr/share/nginx/html
    php:
        image: php:8-fpm
        volumes:
            - ./contents:/usr/share/nginx/html